spring:
  application:
    name: dream-shops
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
